%YAML:1.0
---

dataset_dir: /media/ls/WORK/slam_kitti/dataset/sequences/15

step_freq: 0

num_features: 400
num_features_init: 70
num_features_tracking: 50
num_features_tracking_bad: 40
num_features_needed_for_keyframe: 80
